homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Edmonton

  #customize must nested within homeassistant entity
  customize: !include customize.yaml

# Enables the frontend
frontend:
http:
  api_password: !secret http_password
  # base_url: !secret base_url
  # cors_allowed_origins:
  #  - !secret base_origin
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 7
  trusted_networks:
  - 192.168.1.0/24

updater:
discovery:
conversation:
history:
recorder:
  purge_days: 30
logbook:
logger:
  default: critical
  logs:
    homeassistant.components: info
    homeassistant.components.device_tracker: critical
    homeassistant.components.camera: critical
sun:

# Configuration panel
config:

###########################################
# Includes
###########################################
sensor: !include_dir_merge_list sensor
switch: !include switch.yaml
group: !include group.yaml
camera: !include camera.yaml
media_player: !include media_player.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
# events: !include events.yaml
weblink: !include weblinks.yaml
automation: !include_dir_merge_list automation
# input_select: !include input_select.yaml
# emulated_hue: !include emulated_hue.yaml
# script: !include script.yaml

###########################################
# Third Party Platforms
###########################################

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

ecobee:
  api_key: !secret ecobee_token

light:
  platform: hue
  host: !secret hue_address

tts:
  platform: google

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

wink:
  email: !secret email_account
  password: !secret wink_password
