###########################################
## Media Players                          #
###########################################

- platform: cast

- platform: universal
  name: Living Room
  children:
    - media_player.living_room
    - media_player.living_room_2
