###########################################
## Media Players                          #
###########################################

- platform: cast

- platform: gpmdp
  host: !secret box_address


- platform: universal
  name: Living Room TV
  children:
    - media_player.living_room_tv
    - media_player.living_room_tv_2
    - media_player.living_room_tv_3
    - media_player.living_room
    - media_player.jordan
    - media_player.beth
    - media_player.plex_web_chrome

#- platform: universal
#  name: Guest Bedroom
#  children:
#    - media_player.guest_bedroom_tv

- platform: universal
  name: Speakers
  children:
    - media_player.office_speaker
    - media_player.living_room_speaker

- platform: universal
  name: Remote
  children:

    - media_player.tablet
    - media_player.chris
    - media_player.craigenator
    - media_player.eric1h
    - media_player.fetachz
    - media_player.craigenator
    - media_player.JscoLP
    - media_player.lennonc
    - media_player.osterholta
    - media_player.tohr@yahoo.com
    - media_player.vmmeup
