###########################################
# Download Sensors
###########################################

- platform: sonarr
  api_key: !secret sonarr_api
  host: !secret sonarr_address
  port: !secret sonarr_port
  monitored_conditions:
  - upcoming
  - wanted
  - queue
  days: 1

# - platform: radarr
#   api_key: !secret radarr_api
#   host: !secret radarr_address
#   port: !secret radarr_port
#   monitored_conditions:
#   - upcoming
#   - wanted
#   - queue
#   days: 7

- platform: nzbget
  host: !secret nzbget_host
  port: !secret nzbget_port
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
  - download_rate
  - article_cache
  - average_download_rate
  - download_paused
  - download_rate
  - download_size
  - free_disk_space
  - post_paused
  - remaining_size
  - uptime
