###########################################
# Event Sensors
###########################################

- platform: template
  sensors:
    next_event:
      friendly_name: 'Next Event'
      value_template: '{{ states.calendar.homegiffca.attributes.message }}'

- platform: template
  sensors:
    next_event_time:
      friendly_name: 'Time'
      value_template: '{{ states.calendar.homegiffca.attributes.start_time }}'

- platform: template
  sensors:
    next_event_location:
      friendly_name: 'Location'
      value_template: '{{ states.calendar.homegiffca.attributes.location }}'

###########################################
# Holiday Sensors
###########################################

- platform: template
  sensors:
    next_holiday:
      friendly_name: 'Next Holiday'
      value_template: '{{ states.calendar.holidays_in_canada.attributes.message }}'

- platform: template
  sensors:
    next_holiday_time:
      friendly_name: 'Time'
      value_template: '{{ states.calendar.holidays_in_canada.attributes.start_time }}'
