
###########################################
# Garage Sensors
###########################################

- platform: template
  sensors:
    garage_door:
        value_template: >-
          {%- if is_state("cover.garage_door", "open") %}
              Open
          {%- elif is_state("cover.garage_door", "closed") %}
              Closed
          {%- else %}
              None
          {%- endif %}
