###########################################
# Hub Sensors
###########################################

- platform: template
  sensors:
    wink_update_needed:
        value_template: >-
          {%- if is_state("binary_sensor.wink", "on") %}
              Ok
          {%- elif is_state("binary_sensor.wink", "off") %}
              Update Available
          {%- else %}
              None
          {%- endif %}

- platform: template
  sensors:
    phillipshue_update_needed:
        value_template: >-
          {%- if is_state("binary_sensor.phillipshue", "on") %}
              Ok
          {%- elif is_state("binary_sensor.phillipshue", "off") %}
              Update Available
          {%- else %}
              None
          {%- endif %}
