###########################################
# Speedtest
###########################################
- platform: speedtest
  minute:
  - 0
  - 30
  monitored_conditions:
  - ping
  - download
  - upload


###########################################
# Fast.com
###########################################
#  - platform: fastdotcom
#    minute:
#      - 0
#      - 30

# try sensor.update_fastdotcom sometime
