###########################################
# Plex Activity
###########################################
- platform: plex
  sensors:
  host: !secret plex_address
  username: !secret plex_username
  password: !secret plex_password
  server: plex

###########################################
# TV Sensors
###########################################
- platform: template
  sensors:
    tv_schedule:
      value_template: >-
        {%- for attr in states.sensor.sonarr_upcoming.attributes -%}
        {%- if not attr=="friendly_name" and not attr=="icon" and not attr=="unit_of_measurement" -%}
        {{attr}}{% if not loop.last %}, {% endif %}
        {%- endif -%}
        {%- endfor -%}

- platform: template
  sensors:
    now_playing:
      value_template: '{{ states.media_player.living_room_tv.attributes.media_title }}'
      friendly_name: 'Now Playing'

- platform: template
  sensors:
    music_playing:
#      value_template: '{{ states.media_player.office_speaker.attributes.media_title }}'
      value_template: '{{ states.media_player.office_speaker.attributes.media_title }} {{ states.media_player.office_speaker.attributes.media_artist }}'
      friendly_name: 'Music Playing'

- platform: template
  sensors:
    remote_playing:
      value_template: '{{ states.media_player.remote.attributes.media_title }}'
      friendly_name: 'Playing Remote'
