

###########################################
# Carbon Monoxide Sensor Grouping
###########################################

binary_sensor:


  - platform: template
    sensors:
      co:
        friendly_name: 'Carbon Monoxide'
        device_class: 'gas'
        value_template: >-
          {%- if is_state("sensor.main_floor_nest_protect_co_status", "Ok")
              and is_state("sensor.basement_nest_protect_co_status", "Ok") -%}
          Safe
          {%- else -%}
          On
          {%- endif %}
        entity_id:
          - sensor.main_floor_nest_protect_co_status
          - sensor.basement_nest_protect_co_status

###########################################
# Smoke Sensor Grouping
###########################################

  - platform: template
    sensors:
      smoke:
        friendly_name: 'Smoke'
        device_class: 'smoke'
        value_template: >-
          {%- if is_state("sensor.main_floor_nest_protect_smoke_status", "Ok")
              and is_state("sensor.basement_nest_protect_smoke_status", "Ok") -%}
          Clear
          {%- else -%}
          Smoke Detected
          {%- endif %}
        entity_id:
          - sensor.main_floor_nest_protect_smoke_status
          - sensor.basement_nest_protect_smoke_status


###########################################
# Nest Protect Online Grouping
###########################################

  - platform: template
    sensors:
      nest_protects_online:
        friendly_name: 'Nest Protects'
        device_class: 'connectivity'
        value_template: >-
          {%- if is_state("binary_sensor.main_floor_nest_protect_online", "on")
              and is_state("binary_sensor.basement_nest_protect_online", "on") -%}
          Connected
          {%- else -%}
          Offline
          {%- endif %}
        entity_id:
          - binary_sensor.main_floor_nest_protect_online
          - binary_sensor.basement_nest_protect_online
