###########################################
# CO Sensors
###########################################


binary_sensor:
  - platform: template
    sensors:
      co:
        friendly_name: 'Carbon Monoxide'
        device_class: 'gas'
        value_template: >-
          {%- if is_state("sensor.main_floor_nest_protect_co_status", "Ok")
              and is_state("sensor.basement_nest_protect_co_status", "Ok")
          Off
          {%- else -%}
          On
          {%- endif %}
        entity_id:
          - sensor.main_floor_nest_protect_co_status
          - sensor.basement_nest_protect_co_status

  - platform: template
    sensors:
      smoke:
        friendly_name: 'Smoke'
        device_class: 'smoke'
        value_template: >-
          {%- if is_state("sensor.main_floor_nest_protect_smoke_status", "Ok")
              and is_state("sensor.basement_nest_protect_smoke_status", "Ok")
          Off
          {%- else -%}
          On
          {%- endif %}
        entity_id:
          - sensor.main_floor_nest_protect_smoke_status
          - sensor.basement_nest_protect_smoke_status


  - platform: template
    sensors:
      gates:
        friendly_name: 'Gate'
        device_class: 'opening'
        value_template: >-
          {%- if is_state("binary_sensor.front_gate_opened", "off")
              and is_state("binary_sensor.rear_gate_opened", "off")
          Off
          {%- else -%}
          On
          {%- endif %}
        entity_id:
          - binary_sensor.front_gate_opened
          - binary_sensor.rear_gate_opened
