###########################################
# Gate Sensors
###########################################




###########################################
# Door Sensors
###########################################

cover:
  - platform: myq
    username: !secret email_account
    password: !secret myq_password
    type: chamberlain
