###########################################
# System Sensors
###########################################
- platform: api_streams

- platform: command_line
  command: "/srv/homeassistant/homeassistant_venv/bin/hass --version"
  name: 'HASS Installed'
  scan_interval: 60

- platform: command_line
  name: Login Attempts
  command: "grep -c 'Login attempt' /home/homeassistant/.homeassistant/home-assistant.log"

- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: HASS Release

- platform: command_line
  command: "df -h | grep root | awk '{print $4}'"
  name: "SD Free Space"
  scan_interval: 60

- platform: systemmonitor
  resources:
    - type: since_last_boot
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: template
  sensors:
    since_last_boot_templated:
      value_template: >-
        {%- set slb = states.sensor.since_last_boot.state.split(' ') -%}
        {%- set count = slb | length -%}
        {%- set hms = slb[count - 1] -%}
        {%- set hms_trimmed = hms.split('.')[0] -%}
        {%- set hms_split = hms_trimmed.split(':') -%}
        {%- set hours = hms_split[0] | int -%}
        {%- set minutes = hms_split[1] | int -%}
        {%- set seconds = hms_split[2] | int -%}
        {%- if count == 3 -%}
          {{ slb[0] ~ ' ' ~ slb[1] ~ ' ' }}
        {%- endif -%}
        {%- if hours > 0 -%}
          {%- if hours == 1 -%}
            1 hour
          {%- else -%}
            {{ hours }} hours
          {%- endif -%}
        {%- endif -%}
        {%- if minutes > 0 -%}
          {%- if hours > 0 -%}
            {{ ', ' }}
          {%- endif -%}
          {%- if minutes == 1 -%}
            1 minute
          {%- else -%}
            {{ minutes }} minutes
          {%- endif -%}
        {%- endif -%}
        {%- if seconds > 0 -%}
          {%- if hours > 0 or minutes > 0 -%}
          {%- endif -%}
        {% else %}
            n/a
        {%- endif -%}
