###########################################
# Wink Sensors
###########################################

- platform: template
  sensors:
    wink_status:
        value_template: >-
          {%- if is_state("binary_sensor.wink", "on") %}
              Online
          {%- elif is_state("binary_sensor.wink", "unavailable") %}
              Offline
          {%- else %}
              Error
          {%- endif %}

- platform: template
  sensors:
    wink_firmware_version:
        value_template: '{{ states.binary_sensor.wink.attributes["firmware version"] }}'

- platform: template
  sensors:
    wink_firmware_state:
        value_template: '{{ states.binary_sensor.wink.attributes["update needed"] }}'

- platform: template
  sensors:
    wink_firmware_update_status:
        value_template: >-
          {%- if is_state("sensor.wink_firmware_state", "False") %}
              Current
          {%- elif is_state("sensor.wink_firmware_state", "True") %}
              Update Available
          {%- else %}
              Error
          {%- endif %}
